### ISSUE TITLE
It would be great if the instructions could be made clearer, just needs a small update

### ISSUE THREAD

**Issue by marshalleq** [NabuCasa/sl-web-tools#16]
Checkout the code

With the manifest, I assume I add something to the existing Skyconnect.json?  What do we do with that?

Which operating systems are supported to run this on, Linux?  Mac?

**Comment by puddly** [comment]
What are you trying to do?

**Comment by marshalleq** [comment]
I was trying to update the firmware on my home assistant usb stick.  I'm relatively familiar with running python commands, npm linux etc but not a developer and couldn't ultimately make it work and ended up installing the full home assistant OS in a VM to do it, which I think worked.  I think I figured out that for that stick I didn't have to do anything as it was already in the manifest.  And I assume it's linux, though I tried both Mac and linux and didn't get it to work on either.  I just felt the instructions weren't that clear and needed a bit of extra context.

**Comment by milas** [comment]
I believe the original question here is how to use this as a web component.

To help others, since I just went through this after finding https://github.com/home-assistant/connectzbt1.home-assistant.io/issues/137, here's some notes/instructions.

## Option 1 - Use unpkg.com CDN
This is what the Home Assistant ZBT-1 docs do (see [firmware-update.html](https://github.com/home-assistant/connectzbt1.home-assistant.io/blob/a11022599e4792580a10b873b63484126461edbd/src/firmware-update.html#L31-L34)).

No installation is required in this instance, but it requires the third-party unpkg.com service to load the Javascript at runtime. [Caveat: see below, the component loads libraries from third-party CDNs at runtime for Python execution regardless.]

```html
<script
  type="module"
  src="https://unpkg.com/@nabucasa/sl-web-tools@0.10.1/dist/web/nabucasa-zigbee-flasher.js?module"
></script>
```

## Option 2 - Install as NPM dependency
```shell
npm i @nabucasa/sl-web-tools
```

```html
<script
  type="module"
  src="/node_modules/@nabucasa/sl-web-tools/dist/web/nabucasa-zigbee-flasher.js"
></script>
```

NOTE: Even in this approach, when the component actually connects to a USB device via web serial, it'll load more files from `jsdelivr` (to get the Pyodide runtime) and then Python packages from `pypi.org`.

## Manifest + Firmware
The `nabucasa-zigbee-flasher` web component requires a JSON manifest. There's one available in this repo, but it's behind what's in the Home Assistant ZBT-1 docs, so I'd consider it a schema reference but not rely on it otherwise.

**Comment by puddly** [comment]
Closing, as the original question was about running the web flasher as a tool. For that, you'd want to use https://github.com/NabuCasa/universal-silabs-flasher.

**Comment by milas** [comment]
@puddly Does that mean the web component is deprecated / planned to be archived? I understand the web component packages the "same" Python flasher w/ WASM, but wondering the fate of this repo/code.

**Comment by puddly** [comment]
No, it's still actively used by the community to flash other adapters.
